# -*- coding: utf-8 -*-
"""calculate the average.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoEr9HXTFwf2b9no6rHCRUDmlcQn2phD
"""

# Get the number of years
num_years = int(input("Enter the number of years: "))

total_months = 0
total_rainfall = 0

for year in range(1, num_years + 1):
    print(f"Year {year}:")
    for month in range(1, 13):
        rainfall = float(input(f"Enter the inches of rainfall for month {month}: "))
        total_months += 1
        total_rainfall += rainfall

# Calculate the average rainfall
average_rainfall = total_rainfall / total_months

# Display the results
print("\nResults:")
print(f"Total months: {total_months}")
print(f"Total inches of rainfall: {total_rainfall:.2f}")
print(f"Average rainfall per month: {average_rainfall:.2f}")

